version: '3.7'

services:
  pagination-patterns:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run start:dev
    environment:
      DATABASE_URL: postgresql://dev:dev@postgres/hrs_dev
  postgres:
    image: postgres:12
    ports:
      - 1111:5432
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: hrs_dev
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - hrs-pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
volumes:
  hrs-pgdata:
networks:
  default:
    name: hrs-network
